#!/usr/bin/env node
/**
 * Run: node scripts/setup-env.mjs
 * Creates .env.local with a generated AUTH_SECRET if it doesn't exist.
 */
import { randomBytes } from "crypto";
import { existsSync, writeFileSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const envPath = join(__dirname, "..", ".env.local");

if (existsSync(envPath)) {
  console.log(".env.local already exists.");
  console.log("Make sure it contains: DATABASE_URL=\"file:./dev.db\"");
  process.exit(0);
}

const secret = randomBytes(32).toString("base64");

writeFileSync(envPath, `# Auto-generated by scripts/setup-env.mjs
DATABASE_URL="file:./dev.db"
AUTH_SECRET=${secret}
NEXTAUTH_SECRET=${secret}
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
ANIWATCH_API_URL=
ADMIN_EMAILS=
`);

console.log("✓ .env.local created");
console.log("✓ Run: npx prisma db push && npm run dev");
